# Generated by Django 6.0 on 2026-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_vat_and_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('normal', 'Normal'), ('important', 'Important')], default='normal', max_length=20, verbose_name='客户等级'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quoted'), ('won', 'Won'), ('invalid', 'Invalid')], default='new', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('confirmed', 'Confirmed'), ('won', 'Won'), ('lost', 'Lost')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
