"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# PyMySQL 冒充 MySQLdb；包内默认伪装为 mysqlclient 1.4.x，Django 6 要求 ≥2.2.1
import pymysql

pymysql.version_info = (2, 2, 1, "final", 0)
pymysql.__version__ = "2.2.1"
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-rdkyx&uh+nd=2s$!u=(ai4r^fbl9xkzldk29x32sw#vs+gb3so'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'simpleui',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方库
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'import_export',
    'drf_spectacular',             # API 文档
    'django_extensions',
    'debug_toolbar',               # 开发调试工具
    'ckeditor',                    # 富文本编辑器（用于 About Us 等页面）
    'simple_history',              # 修改历史记录

    # 你的自定义 App
    'core',
    'brands',
    'products',
    'company',
    'users',
    'menus',
    'api',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',   # 必须放在最前面
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # 开发时启用
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ====================== 数据库（使用 PyMySQL） ======================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'achievers_db',           # 请确保这个数据库已创建
        'USER': 'root',
        'PASSWORD': 'Root@123456',      # ←←← 改成你自己的密码
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# ====================== Redis + 缓存 ======================
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',   # 本地开发默认端口
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# ====================== 静态文件 & 媒体文件（产品图片） ======================
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ====================== CORS 配置（React 前端必备） ======================
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",      # React 默认端口
    "http://127.0.0.1:3000",
]
CORS_ALLOW_CREDENTIALS = True

# ====================== REST Framework 配置 ======================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',   # 默认需要登录，可按需调整
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',   # 支持 Swagger
}

# ====================== SimpleJWT 配置 ======================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ====================== drf-spectacular API 文档配置 ======================
SPECTACULAR_SETTINGS = {
    'TITLE': 'Achievers Automation API',
    'DESCRIPTION': '工业自动化产品后台管理系统 API',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# ====================== django-simpleui 配置 ======================
SIMPLEUI_DEFAULT_THEME = 'green'          # 可选主题：blue、green、dark 等
SIMPLEUI_LOGO = ''                        # 可放你自己的 logo 图片路径
SIMPLEUI_HOME_INFO = False                # 隐藏首页右侧信息
SIMPLEUI_ANALYSIS = False                 # 关闭使用分析

# ====================== 其他基础配置 ======================
LANGUAGE_CODE = 'zh-hans'                 # 中文界面
TIME_ZONE = 'Asia/Shanghai'
USE_I18N = True
USE_TZ = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# ====================== 开发环境调试工具 ======================
INTERNAL_IPS = ['127.0.0.1']              # debug_toolbar 使用

SILENCED_SYSTEM_CHECKS = ['ckeditor.W001']