# Generated by Django 6.0 on 2026-04-26 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name_zh', models.CharField(max_length=128, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=128, verbose_name='英文名称')),
                ('iso_alpha_2', models.CharField(db_index=True, max_length=2, unique=True, verbose_name='ISO 3166-1 alpha-2')),
                ('iso_alpha_3', models.CharField(blank=True, max_length=3, verbose_name='ISO 3166-1 alpha-3')),
                ('phone_code', models.CharField(blank=True, help_text='如 +86、+1', max_length=8, verbose_name='国际电话区号')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '国家/地区',
                'verbose_name_plural': '国家/地区',
                'db_table': 'Country',
                'ordering': ['sort_order', 'iso_alpha_2', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StateProvince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name_zh', models.CharField(max_length=128, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=128, verbose_name='英文名称')),
                ('code', models.CharField(blank=True, help_text='如省简称、美州两字母等，无则留空', max_length=32, verbose_name='区划/州代码')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='regions.country', verbose_name='国家/地区')),
            ],
            options={
                'verbose_name': '省/州',
                'verbose_name_plural': '省/州',
                'db_table': 'StateProvince',
                'ordering': ['country', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name_zh', models.CharField(max_length=128, verbose_name='中文名称')),
                ('name_en', models.CharField(max_length=128, verbose_name='英文名称')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='regions.stateprovince', verbose_name='省/州')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'City',
                'ordering': ['state', 'sort_order', 'id'],
            },
        ),
    ]
