# Generated by Django 6.0 on 2026-04-26 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='类目名称')),
                ('slug', models.SlugField(max_length=280, verbose_name='URL 标识')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('external_slug', models.CharField(blank=True, help_text='例如 supplier-4327614-endress-hauser-instruments', max_length=300, verbose_name='外部站点 slug')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='brands.brand', verbose_name='品牌')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory', verbose_name='上级类目')),
            ],
            options={
                'verbose_name': '产品类目',
                'verbose_name_plural': '产品类目',
                'db_table': 'ProductCategory',
                'ordering': ['brand', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('sku', models.CharField(blank=True, db_index=True, help_text='厂商订货号或型号，可与站点标题中一致。', max_length=160, null=True, verbose_name='订货号 / 型号')),
                ('name', models.CharField(max_length=500, verbose_name='名称')),
                ('slug', models.SlugField(max_length=520, unique=True, verbose_name='URL 标识')),
                ('summary', models.CharField(blank=True, max_length=1000, verbose_name='摘要')),
                ('description', models.TextField(blank=True, verbose_name='详情')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='JSON，存放电压、协议、通道数等差异化字段。', verbose_name='扩展属性')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='原产地')),
                ('source_url', models.URLField(blank=True, max_length=800, verbose_name='来源页 URL')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='同步或爬虫侧主键，可选。', max_length=120, verbose_name='外部系统 ID')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '上架'), ('archived', '归档')], db_index=True, default='draft', max_length=16, verbose_name='状态')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.productcategory', verbose_name='类目')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'Product',
                'ordering': ['category', 'sort_order', 'sku', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('image_url', models.URLField(max_length=800, verbose_name='图片 URL')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='替代文本')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主图')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'db_table': 'ProductImage',
                'ordering': ['product', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='uniq_productcategory_brand_slug'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('category', 'sku'), name='uniq_product_category_sku_when_sku_set'),
        ),
    ]
