# Generated by Django 6.0 on 2026-04-26 06:12

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('company_name', models.CharField(default='Achievers Automation Limited', max_length=200, verbose_name='公司英文名称')),
                ('company_name_zh', models.CharField(blank=True, max_length=200, verbose_name='公司中文名称')),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='一句话简介')),
                ('business_type', models.CharField(blank=True, help_text='例如：Distributor/Wholesaler, Trading Company', max_length=300, verbose_name='经营类型')),
                ('main_market', models.CharField(blank=True, default='Worldwide', max_length=200, verbose_name='主要市场')),
                ('year_established', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='成立年份')),
                ('employees_range', models.CharField(blank=True, help_text='例如：10~15', max_length=64, verbose_name='人员规模')),
                ('annual_sales_range', models.CharField(blank=True, help_text='例如：3000000-5000000（USD 等由前端文案说明）', max_length=120, verbose_name='年销售额区间')),
                ('export_percentage', models.CharField(blank=True, help_text='例如：60% - 70%', max_length=64, verbose_name='出口占比')),
                ('main_brands_text', models.TextField(blank=True, help_text='与站点 Brands 栏一致，可多行。', verbose_name='主营品牌（文本）')),
                ('highlight_pillars', models.JSONField(blank=True, default=list, help_text='JSON 数组，每项形如 {"title": "HIGH QUALITY", "body": "..."}', verbose_name='核心优势（四宫格）')),
                ('content_introduction', ckeditor.fields.RichTextField(blank=True, verbose_name='Introduction 正文')),
                ('content_history', ckeditor.fields.RichTextField(blank=True, verbose_name='History 正文')),
                ('content_service', ckeditor.fields.RichTextField(blank=True, verbose_name='Service 正文')),
                ('content_team', ckeditor.fields.RichTextField(blank=True, verbose_name='Our Team 正文')),
                ('legal_disclaimer', ckeditor.fields.RichTextField(blank=True, verbose_name='法律声明 / Disclaimer')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=64, verbose_name='电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('offices_description', models.TextField(blank=True, help_text='例如香港、深圳办公室及团队说明。', verbose_name='办公地点说明')),
                ('profile_video_url', models.URLField(blank=True, max_length=500, verbose_name='公司介绍视频 URL')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='company/about/', verbose_name='主图（如仓库/公司图）')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
                'db_table': 'CompanyAbout',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('company_name', models.CharField(default='Achievers Automation Limited', max_length=200, verbose_name='公司显示名称')),
                ('registered_address', models.TextField(blank=True, help_text='例如香港办公地址全文。', verbose_name='注册/办公地址')),
                ('factory_address', models.TextField(blank=True, verbose_name='工厂/仓库地址')),
                ('work_hours', models.CharField(blank=True, help_text='例如：8:00-19:00(Beijing time)', max_length=200, verbose_name='营业时间')),
                ('business_phone_note', models.TextField(blank=True, help_text='可写多行，如 Working / Nonworking 分机说明。', verbose_name='业务电话说明')),
                ('inquiry_hint', models.CharField(blank=True, help_text='例如：Send your inquiry directly to us', max_length=300, verbose_name='询盘表单提示文案')),
            ],
            options={
                'verbose_name': '联系我们（页头信息）',
                'verbose_name_plural': '联系我们（页头信息）',
                'db_table': 'CompanyContact',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=120, verbose_name='姓名')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='职位')),
                ('business_phone', models.CharField(blank=True, max_length=64, verbose_name='业务电话')),
                ('whatsapp', models.CharField(blank=True, max_length=64, verbose_name='WhatsApp')),
                ('wechat', models.CharField(blank=True, max_length=64, verbose_name='WeChat')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='显示')),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='company.companycontact', verbose_name='所属联系页')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'db_table': 'ContactPerson',
                'ordering': ['contact_page', 'sort_order', 'id'],
            },
        ),
    ]
