# Generated by Django 6.0 on 2026-04-19 13:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Achievers Automation Limited', max_length=200, verbose_name='公司英文名称')),
                ('company_name_zh', models.CharField(blank=True, max_length=200, verbose_name='公司中文名称')),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='一句话简介')),
                ('business_type', models.CharField(blank=True, help_text='例如：Distributor/Wholesaler, Trading Company', max_length=300, verbose_name='经营类型')),
                ('main_market', models.CharField(blank=True, default='Worldwide', max_length=200, verbose_name='主要市场')),
                ('year_established', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='成立年份')),
                ('employees_range', models.CharField(blank=True, help_text='例如：10~15', max_length=64, verbose_name='人员规模')),
                ('annual_sales_range', models.CharField(blank=True, help_text='例如：3000000-5000000（USD 等由前端文案说明）', max_length=120, verbose_name='年销售额区间')),
                ('export_percentage', models.CharField(blank=True, help_text='例如：60% - 70%', max_length=64, verbose_name='出口占比')),
                ('main_brands_text', models.TextField(blank=True, help_text='与站点 Brands 栏一致，可多行。', verbose_name='主营品牌（文本）')),
                ('highlight_pillars', models.JSONField(blank=True, default=list, help_text='JSON 数组，每项形如 {"title": "HIGH QUALITY", "body": "..."}', verbose_name='核心优势（四宫格）')),
                ('content_introduction', ckeditor.fields.RichTextField(blank=True, verbose_name='Introduction 正文')),
                ('content_history', ckeditor.fields.RichTextField(blank=True, verbose_name='History 正文')),
                ('content_service', ckeditor.fields.RichTextField(blank=True, verbose_name='Service 正文')),
                ('content_team', ckeditor.fields.RichTextField(blank=True, verbose_name='Our Team 正文')),
                ('legal_disclaimer', ckeditor.fields.RichTextField(blank=True, verbose_name='法律声明 / Disclaimer')),
                ('contact_person', models.CharField(blank=True, max_length=120, verbose_name='联系人')),
                ('contact_phone', models.CharField(blank=True, max_length=64, verbose_name='电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('offices_description', models.TextField(blank=True, help_text='例如香港、深圳办公室及团队说明。', verbose_name='办公地点说明')),
                ('profile_video_url', models.URLField(blank=True, max_length=500, verbose_name='公司介绍视频 URL')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='company/about/', verbose_name='主图（如仓库/公司图）')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '关于我们',
                'verbose_name_plural': '关于我们',
            },
        ),
    ]
