# Generated by Django 6.0 on 2026-04-19 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Achievers Automation Limited', max_length=200, verbose_name='公司显示名称')),
                ('registered_address', models.TextField(blank=True, help_text='例如香港办公地址全文。', verbose_name='注册/办公地址')),
                ('factory_address', models.TextField(blank=True, verbose_name='工厂/仓库地址')),
                ('work_hours', models.CharField(blank=True, help_text='例如：8:00-19:00(Beijing time)', max_length=200, verbose_name='营业时间')),
                ('business_phone_note', models.TextField(blank=True, help_text='可写多行，如 Working / Nonworking 分机说明。', verbose_name='业务电话说明')),
                ('inquiry_hint', models.CharField(blank=True, help_text='例如：Send your inquiry directly to us', max_length=300, verbose_name='询盘表单提示文案')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
            ],
            options={
                'verbose_name': '联系我们（页头信息）',
                'verbose_name_plural': '联系我们（页头信息）',
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='姓名')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='职位')),
                ('business_phone', models.CharField(blank=True, max_length=64, verbose_name='业务电话')),
                ('whatsapp', models.CharField(blank=True, max_length=64, verbose_name='WhatsApp')),
                ('wechat', models.CharField(blank=True, max_length=64, verbose_name='WeChat')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='显示')),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='company.companycontact', verbose_name='所属联系页')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['contact_page', 'sort_order', 'id'],
            },
        ),
    ]
