# Generated by Django 6.0 on 2026-04-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('path', models.CharField(blank=True, help_text='如 /admin/products；仅作分组时留空', max_length=255, verbose_name='前端路由')),
                ('icon', models.CharField(blank=True, help_text='Ant Design 图标组件名，如 DashboardOutlined', max_length=64, verbose_name='图标')),
                ('permission_code', models.CharField(blank=True, db_index=True, help_text='对应 Permission.code；留空表示登录即可见', max_length=128, verbose_name='所需权限')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.navmenuitem', verbose_name='上级')),
            ],
            options={
                'verbose_name': '导航菜单项',
                'verbose_name_plural': '导航菜单项',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
