# Generated by Django 6.0 on 2026-04-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='名称')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL 标识')),
                ('short_name', models.CharField(blank=True, help_text='列表或徽标旁展示用，可与 name 相同。', max_length=120, verbose_name='简称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('website', models.URLField(blank=True, verbose_name='官网')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
