# Generated by Django 6.0 on 2026-04-18 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_system', models.BooleanField(default=False, help_text='内置角色不建议删除，仅可通过后台管理权限集合。', verbose_name='系统内置')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_profiles', to='users.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户扩展(RBAC)',
                'verbose_name_plural': '用户扩展(RBAC)',
            },
        ),
    ]
