# Generated by Django 6.0 on 2026-04-26 06:12

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('code', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'Permission',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='租户代码')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('subscription_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='B2B SaaS：按公司维度记录；与单用户会员解耦。', null=True, verbose_name='订阅/合同到期时间')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'Tenant',
                'ordering': ['code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='角色代码')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_system', models.BooleanField(default=False, help_text='内置角色不建议删除，仅可通过后台管理权限集合。', verbose_name='系统内置')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='users.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'Role',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('account_status', models.CharField(choices=[('active', '正常'), ('suspended', '已停用'), ('pending', '待审核/待激活'), ('closed', '已关闭')], db_index=True, default='active', max_length=20, verbose_name='账号状态')),
                ('failed_login_count', models.PositiveIntegerField(default=0, verbose_name='连续登录失败次数')),
                ('lockout_started_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='账户锁定起始时间')),
                ('mfa_enabled', models.BooleanField(db_index=True, default=False, verbose_name='启用双因素认证')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500, verbose_name='头像地址')),
                ('gender', models.CharField(blank=True, choices=[('', '未设置'), ('male', '男'), ('female', '女'), ('other', '其他')], default='', max_length=8, verbose_name='性别')),
                ('phone', models.CharField(blank=True, db_index=True, default='', help_text='国际 E.164，如 +8613800138000', max_length=20, verbose_name='手机号码 (E.164)')),
                ('email_verified_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='邮箱验证完成时间')),
                ('phone_verified_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='手机验证完成时间')),
                ('user_kind', models.CharField(choices=[('platform', '平台运营方'), ('tenant', '企业用户')], db_index=True, default='tenant', help_text='平台 = 可跨租户的运营/支持；企业 = 客户侧成员，权限按 TenantMembership 生效。', max_length=20, verbose_name='身份类型')),
                ('wechat_bound_at', models.DateTimeField(blank=True, null=True, verbose_name='微信绑定时间')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='非结构化键值，业务自定义', verbose_name='扩展字段')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('default_tenant', models.ForeignKey(blank=True, help_text='多公司成员时，登录后默认进入的组织；可配合请求头 X-Tenant-Id 切换。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_default_tenant', to='users.tenant', verbose_name='默认工作租户')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'UserInfo',
                'ordering': ['-date_joined', 'id'],
            },
            managers=[
                ('objects', users.models.UserInfoManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('pending_approval', models.BooleanField(db_index=True, default=False, help_text='公开注册且尚未通过管理员审批时为 True；审批通过后清零。', verbose_name='待审批注册')),
                ('roles', models.ManyToManyField(blank=True, related_name='user_profiles', to='users.role', verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户扩展(RBAC)',
                'verbose_name_plural': '用户扩展(RBAC)',
                'db_table': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('invited', '已邀请'), ('active', '在册'), ('suspended', '已暂停')], db_index=True, default='active', max_length=16, verbose_name='成员状态')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='职位/备注')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_memberships', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
                ('roles', models.ManyToManyField(blank=True, related_name='tenant_memberships', to='users.role', verbose_name='角色（本租户内）')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '租户成员',
                'verbose_name_plural': '租户成员',
                'db_table': 'TenantMembership',
                'ordering': ['tenant_id', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='users_tenantmembership_user_tenant_uniq')],
            },
        ),
    ]
