# Generated by Django 6.0 on 2026-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_backfill_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_approval',
            field=models.BooleanField(db_index=True, default=False, help_text='公开注册且尚未通过管理员审批时为 True；审批通过后清零。', verbose_name='待审批注册'),
        ),
    ]
